name: update-readme

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  job_3: # build Mermaid_Visualization
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version you need
      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any dependencies
      - name: Run the update_readme script
        run: python scripts/update_readme.py
      - name: List all contents in the branch
        run: |
          git ls-tree --full-tree -r HEAD
      - name: Commit files
              git config --local user.name "matze2402"
              git config --local user.email "matthias.gacka@tu-dortmund.de"
              git add README.md
              git commit -m "Update README.md"
              git push
              
            
